apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: development cluster
spec:
  gke:
    cluster: projects/cloudside-academy/locations/us-central1/clusters/cluster-ad
    workerPool: 'projects/cloudside-academy/locations/us-central1/workerPools/worker-pool-ad'
