apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: development cluster
gke:
  cluster: projects/cloudside-academy/locations/us-central1/clusters/cluster-ad
  internalIp: "10.121.0.0/28"
executionConfigs:
- usages:
  - DEPLOY
  privatePool:
    workerPool: "projects/cloudside-academy/locations/us-central1/workerPools/worker-pool-ad"
- usages:
  - RENDER
  - PREDEPLOY
  - VERIFY
  - POSTDEPLOY

      
